package com.corhuila.TallerMecanico.Util;

public enum Permission {

    // VEHICULOS
    READ_ALL_VEHICLES,
    READ_BY_PLATE_VEHICLES,
    SAVE_ONE_VEHICLE,
    UPDATE_ONE_VEHICLE,
    DELETE_ONE_VEHICLE,
    // ORDEN
    SAVE_ONE_ORDER,
    UPDATE_ONE_ORDER,
    DELETE_ONE_ORDER,
    // PERSONA
    SAVE_ONE_PERSON,
    UPDATE_ONE_PERSON,
    DELETE_ONE_PERSON,
    // SERVICIO
    SAVE_ONE_SERVICE,
    UPDATE_ONE_SERVICE,
    DELETE_ONE_SERVICE,
    // INVENTARIO
    SAVE_ONE_INVENTORY,
    UPDATE_ONE_INVENTORY,
    DELETE_ONE_INVENTORY;

}
